

(in-package :clboy)
(defparameter *memory* (make-array #x10000 :element-type '(unsigned-byte 8)))
(defun write-memory-at-addr (gb addr val)
  (setf (aref *memory* addr) val))

(defun read-memory-at-addr (gb addr)
  (aref *memory* addr))

(defpackage :clboy-test
  (:use :common-lisp :clboy :try)
  (:import-from :clboy
                #:gbcpu-pc
                #:gbcpu-a
                #:gbcpu-b
                #:gbcpu-c
                #:gbcpu-d
                #:gbcpu-e
                #:gbcpu-h
                #:gbcpu-l
                #:gbcpu-sp
                #:gbcpu-flags
                #:gbcpu-halted
                #:gbcpu-int-ena
                #:copy-gbflags
                #:gbflags-z
                #:gbflags-n
                #:gbflags-h
                #:gbflags-c
                #:make-gb
                #:make-gbflags
                #:gb-cpu
                #:gb-stopped?
                #:step-cpu
                #:flags-into-byte
                #:flags-from-byte
                #:read-memory-at-addr
                #:write-memory-at-addr
                #:get-address-from-reg-pair
                #:set-reg-pair-bc-to-val
                #:set-reg-pair-de-to-val
                #:set-reg-pair-hl-to-val
                #:get-byte-at-bc
                #:get-byte-at-de
                #:get-byte-at-hl
                #:set-byte-at-bc
                #:set-byte-at-de
                #:set-byte-at-hl
                #:push-addr-on-stack
                #:peek-addr-from-stack)
  (:export #:test-cpu))

(in-package :clboy-test)


(deftest test-cpu ()
  (test-cpu-8bit-ops)
  (test-cpu-16bit-ops)
  (test-jp-ops)
  (test-call-ops)
  (test-ret-ops)
  (test-rst-ops)
  (test-special)
  )

(deftest test-cpu-8bit-ops ()
  (test-cpu-8bit-load-ops)
  (test-cpu-8bit-arith-and-logic-ops)
  (test-cpu-8bit-bit-ops)
  (loop for init-val in (list 0 #xff #xf0 #x0f) do
        (test-cpl init-val)
        (test-daa init-val))
  (test-ccf)
  (test-scf))

(deftest test-cpu-8bit-load-ops ()
  (loop for fin-val in (list 0 #xff #xf0 #x0f) do
    (test-8bit-load-ops fin-val)
    (test-8bit-load-regpair-ops fin-val)
    (test-8bit-load-imm-ops fin-val)
    (test-ld-a-into-byte fin-val)
    (test-ld-byte-into-a fin-val)
    (test-ld-sp-with-rel-into-hl fin-val)
    (test-add-rel-to-sp fin-val)
    (test-himem-load-ops fin-val)))

(deftest test-cpu-8bit-arith-and-logic-ops ()
  (loop for init-val in (list 0 #xff #xf0 #x0f) do
    (loop for fin-val in (list 0 #xff #xf0 #x0f) do
      (test-8bit-add-ops init-val fin-val)
      (test-adc-ops init-val fin-val)
      (test-sub-ops init-val fin-val)
      (test-sbc-ops init-val fin-val)
      (test-and-ops init-val fin-val)
      (test-xor-ops init-val fin-val)
      (test-or-ops init-val fin-val)
      (test-cp-ops init-val fin-val))
    (test-8bit-inc-ops init-val)
    (test-8bit-dec-ops init-val)))

(deftest test-cpu-8bit-bit-ops ()
  (loop for init-val in (list 0 #xff #xf0 #x0f) do
    (test-rlca-op #x07 init-val)
    (test-rrca-op #x0f init-val)
    (test-rla-op #x17 init-val)
    (test-rra-op #x1f init-val)
    (test-rlc-ops init-val)
    (test-rrc-ops init-val)
    (test-rl-ops init-val)
    (test-rr-ops init-val)
    (test-sla-ops init-val)
    (test-sra-ops init-val)
    (test-srl-ops init-val)
    (test-swap-ops init-val)
    (test-bit-ops init-val)
    (test-set-bit-ops init-val)
    (test-reset-bit-ops init-val)))

(deftest test-cpu-16bit-ops ()
  (loop for init-val in (list 0 #x00ff #xff00 #xffff) do
    (loop for fin-val in (list 0 #x00ff #xff00 #xffff) do
      (test-16bit-add-ops init-val fin-val))
    (test-16bit-load-ops init-val)
    (test-16bit-inc-ops init-val)
    (test-16bit-dec-ops init-val)
    (test-ld-sp-into-addr init-val)
    (test-push-ops init-val)
    (test-pop-ops init-val)))

(deftest test-special ()
  (test-nop)
  (test-stop)
  (test-halt)
  (test-di)
  (test-ei))

(deftest test-nop ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x00)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))))

(deftest test-stop ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x10)
    (write-memory-at-addr gb (+ init-pc 1) #x00)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (gb-stopped? gb))
    (format t "~A~%" (gb-stopped? gb))
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))))

(deftest test-halt ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x76)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-halted cpu) 1))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))))

(deftest test-di ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xf3)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-int-ena cpu) 0))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))))

(deftest test-ei ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xfb)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-int-ena cpu) 1))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))))

(deftest test-daa (init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu)))
         (res (if (= (gbflags-n init-flags) 0)
                (+ init-val (if (> (logand init-val #x0f) #x09) #x6 0) (if (> (logand init-val #xf0) #x90) #x60 0))
                (- init-val (if (> (logand init-val #x0f) #x09) #x6 0) (if (> (logand init-val #xf0) #x90) #x60 0)))))
    (write-memory-at-addr gb init-pc #x27)
    (setf (gbcpu-pc cpu) init-pc)
    (setf (gbcpu-a cpu) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-a cpu) (logand res #xff)))
    (is (= (gbflags-z (gbcpu-flags cpu)) (if (= (logand res #xff) #x0) 1 0)))
    (is (= (gbflags-n (gbcpu-flags cpu)) (gbflags-n init-flags)))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (> init-val #x90) 1 0)))))

(deftest test-scf ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x37)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbflags-z (gbcpu-flags cpu)) (gbflags-z init-flags)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) 1))))

(deftest test-cpl (init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x2f)
    (setf (gbcpu-pc cpu) init-pc)
    (setf (gbcpu-a cpu) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-a cpu) (logxor init-val #xff)))
    (is (= (gbflags-z (gbcpu-flags cpu)) (gbflags-z init-flags)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 1))
    (is (= (gbflags-h (gbcpu-flags cpu)) 1))
    (is (= (gbflags-c (gbcpu-flags cpu)) (gbflags-c init-flags)))))

(deftest test-ccf ()
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x3f)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbflags-z (gbcpu-flags cpu)) (gbflags-z init-flags)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (logxor (gbflags-c init-flags) #x1)))))

(deftest test-rlca-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val 1) #xff) (ash init-val -7))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :a init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (get-reg gb :a) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x80) #x80) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu)) 0))))

(deftest test-rrca-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val -1) #xff) (ash (logand init-val #x1) 7))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :a init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (get-reg gb :a) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu)) 0))))

(deftest test-rla-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (carry (gbflags-c (gbcpu-flags cpu)))
         (res (logior (logand (ash init-val 1) #xff) carry)))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :a init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (get-reg gb :a) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x80) #x80) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu)) 0))))

(deftest test-rra-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (carry (gbflags-c (gbcpu-flags cpu)))
         (res (logior (logand (ash init-val -1) #xff) (ash carry 7))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :a init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (get-reg gb :a) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu)) 0))))

(deftest test-load-op (op dest src fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (when (= init-pc (get-address-from-reg-pair (gbcpu-h cpu) (gbcpu-l cpu)))
      (setf init-pc (+ init-pc 1)))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb src fin-val)
    (step-cpu cpu gb)
    (if (eq src :imm)
      (is (= (gbcpu-pc cpu) (+ init-pc 2)))
      (if (eq src :imm16)
        (is (= (gbcpu-pc cpu) (+ init-pc 3)))
        (is (= (gbcpu-pc cpu) (+ init-pc 1)))))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb dest) fin-val)
        :ctx ("During opcode ~X the ~A register should match ~A" op dest fin-val))))

(deftest test-8bit-load-ops (fin-val)
  (loop for op from #x40 to #x7f
        when (not (= op #x76)) do
        (test-load-op op (get-dest-reg-from-op op) (get-src-reg-from-op op) fin-val)))

(deftest test-8bit-load-imm-ops (fin-val)
  (loop for op in '((#x06 :b) (#x0e :c) (#x16 :d) (#x1e :e)
                    (#x26 :h) (#x2e :l) (#x36 :<hl) (#x3e :a)) do
        (test-load-op (car op) (cadr op) :imm fin-val)))

(deftest test-load-regpair-op (op dest src regpair-modifier init-regpair fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (reg-pair (if (eq src :a) dest src))
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb reg-pair init-regpair)
    (if (eq src :a)
      (set-reg gb src fin-val)
      (write-memory-at-addr gb init-regpair fin-val))
    (step-cpu cpu gb)
    (if (eq src :imm)
      (is (= (gbcpu-pc cpu) (+ init-pc 2)))
      (if (eq src :imm16)
        (is (= (gbcpu-pc cpu) (+ init-pc 3)))
        (is (= (gbcpu-pc cpu) (+ init-pc 1)))))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (if (eq regpair-modifier :inc)
      (is (= (get-reg gb reg-pair) (+ init-regpair 1)))
      (if (eq regpair-modifier :dec)
        (is (= (get-reg gb reg-pair) (- init-regpair 1)))
        (is (= (get-reg gb reg-pair) init-regpair))))
    (if (eq dest :a)
      (is (= (get-reg gb dest) fin-val)
          :ctx ("During opcode ~X the ~A register should match ~A" op dest fin-val))
      (is (= (read-memory-at-addr gb init-regpair) fin-val)
          :ctx ("During opcode ~X the ~A register should match ~A" op dest fin-val)))))

(deftest test-8bit-load-regpair-ops (fin-val)
  (loop for op in '((#x02 :bc :a nil) (#x0a :a :bc nil) (#x12 :de :a nil) (#x1a :a :de nil)
                    (#x22 :hl :a :inc) (#x2a :a :hl :inc) (#x32 :hl :a :dec) (#x3a :a :hl :dec)) do
        (test-load-regpair-op (car op) (cadr op) (caddr op) (cadddr op) #xc500 fin-val)))

(deftest test-16bit-load-ops (fin-val)
  (loop for op in '((#x01 :bc :imm16) (#x11 :de :imm16) (#x21 :hl :imm16) (#x31 :sp :imm16)
                    (#xf9 :sp :hl)) do
        (test-load-op (car op) (cadr op) (caddr op) fin-val)))

(deftest test-ld-sp-into-addr (fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #x08)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :sp fin-val)
    (set-reg gb :imm16 #xd600)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 3)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (logior (read-memory-at-addr gb #xd600)
                   (ash (read-memory-at-addr gb #xd601) 8)) fin-val))))

(deftest test-ld-a-into-byte (fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xea)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :a fin-val)
    (set-reg gb :imm16 #xd600)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 3)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (read-memory-at-addr gb #xd600) fin-val))))

(deftest test-ld-byte-into-a (fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xfa)
    (setf (gbcpu-pc cpu) init-pc)
    (write-memory-at-addr gb #xd600 fin-val)
    (set-reg gb :imm16 #xd600)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 3)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb :a) fin-val))))

(deftest test-ld-sp-with-rel-into-hl (rel-byte)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-sp #xc500)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xf8)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :sp init-sp)
    (set-reg gb :imm rel-byte)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb :hl) (logand (+ init-sp (if (= (logand rel-byte #x80) 0) rel-byte (logior rel-byte #xff00))) #xffff)))))

(deftest test-add-rel-to-sp (rel-byte)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-sp #xc500)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc #xe8)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb :sp init-sp)
    (set-reg gb :imm rel-byte)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb :sp) (logand (+ init-sp (if (= (logand rel-byte #x80) 0) rel-byte (logior rel-byte #xff00))) #xffff)))))

(deftest test-8bit-inc-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu)))
         (res (logand (+ init-val 1) #xff)))
    (when (eq reg :<hl)
      (set-reg-pair-hl-to-val cpu #xc100))
    (set-reg gb reg init-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) (if (> (+ (logand init-val #xf) 1) #xf) 1 0)))
    (is (= (gbflags-c (gbcpu-flags cpu)) (gbflags-c init-flags)))
    (is (= (get-reg gb reg) res)
        :ctx ("During opcode ~X the ~A register should hold the result of ~A + ~A" op reg init-val 1))))

(deftest test-8bit-inc-ops (init-val)
  (loop for op in '((#x04 :b) (#x0c :c) (#x14 :d) (#x1c :e)
                    (#x24 :h) (#x2c :l) (#x34 :<hl) (#x3c :a)) do
        (test-8bit-inc-op (car op) (cadr op) init-val)))

(deftest test-8bit-dec-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu)))
         (res (logand (- init-val 1) #xff)))
    (when (eq reg :<hl)
      (set-reg-pair-hl-to-val cpu #xc100))
    (set-reg gb reg init-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 1))
    (is (= (gbflags-h (gbcpu-flags cpu)) (if (= (logand init-val #xf) 0) 1 0)))
    (is (= (gbflags-c (gbcpu-flags cpu)) (gbflags-c init-flags)))
    (is (= (get-reg gb reg) res)
        :ctx ("During opcode ~X the ~A register should hold the result of ~A - ~A" op reg init-val 1))))

(deftest test-8bit-dec-ops (init-val)
  (loop for op in '((#x05 :b) (#x0d :c) (#x15 :d) (#x1d :e)
                    (#x25 :h) (#x2d :l) (#x35 :<hl) (#x3d :a)) do
        (test-8bit-dec-op (car op) (cadr op) init-val)))

(deftest test-16bit-inc-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu)))
         (res (logand (+ init-val 1) #xffff)))
    (when (eq reg :<hl)
      (set-reg-pair-hl-to-val cpu #xc100))
    (set-reg gb reg init-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb reg) res)
        :ctx ("During opcode ~X the ~A register should hold the result of ~A + ~A" op reg init-val 1))))

(deftest test-16bit-inc-ops (init-val)
  (loop for op in '((#x03 :bc) (#x13 :de) (#x23 :hl) (#x33 :sp)) do
        (test-16bit-inc-op (car op) (cadr op) init-val)))

(deftest test-16bit-dec-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (flags-into-byte (gbcpu-flags cpu)))
         (res (logand (- init-val 1) #xffff)))
    (when (eq reg :<hl)
      (set-reg-pair-hl-to-val cpu #xc100))
    (set-reg gb reg init-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (get-reg gb reg) res)
        :ctx ("During opcode ~X the ~A register should hold the result of ~A - ~A" op reg init-val 1))))

(deftest test-16bit-dec-ops (init-val)
  (loop for op in '((#x0b :bc) (#x1b :de) (#x2b :hl) (#x3b :sp)) do
        (test-16bit-dec-op (car op) (cadr op) init-val)))

(deftest test-acc-op (op src init-val other-val res res-flags-byte)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg-pair-hl-to-val cpu #xc100)
    (set-reg gb :a init-val)
    (set-reg gb src other-val)
    (step-cpu cpu gb)
    (if (eq src :imm)
      (is (= (gbcpu-pc cpu) (+ init-pc 2)))
      (is (= (gbcpu-pc cpu) (+ init-pc 1))))
    (is (= (flags-into-byte (gbcpu-flags cpu)) res-flags-byte))
    (is (= (gbcpu-a cpu) res)
        :ctx ("During opcode ~X the :A register should hold the result of ~A" op res))))

(deftest test-8bit-add-ops (init-val other-val)
  (loop for op in '((#x80 :b) (#x81 :c) (#x82 :d) (#x83 :e)
                    (#x84 :h) (#x85 :l) (#x86 :<hl) (#x87 :a) (#xc6 :imm)) do
    (if (= (car op) #x87)
      (test-acc-op (car op) (cadr op) init-val init-val (logand (+ init-val init-val) #xff) (flags-into-byte (calc-8bit-add-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logand (+ init-val other-val) #xff) (flags-into-byte (calc-8bit-add-flags init-val other-val))))))

(defun calc-8bit-add-flags (init-val other-val &optional (carry 0))
  (make-gbflags
    :z (if (= (logand (+ init-val other-val carry) #xff) #x0) 1 0)
    :n  0
    :h (if (> (+ (logand init-val #xf) (logand other-val #xf) carry) #xf) 1 0)
    :c (if (> (+ init-val other-val carry) #xff) 1 0)))

(defun calc-16bit-add-flags (init-val other-val)
  (make-gbflags
    :z (if (= (logand (+ init-val other-val) #xffff) #x0) 1 0)
    :n  0
    :h (if (> (+ (logand init-val #xfff) (logand other-val #xfff)) #xfff) 1 0)
    :c (if (> (+ init-val other-val) #xffff) 1 0)))

(deftest test-16bit-add-op (op src init-val other-val res res-flag-byte)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu))))
    (set-reg gb :hl init-val)
    (set-reg gb src other-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbflags-z (gbcpu-flags cpu)) (gbflags-z init-flags)))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu))
           (if (> (+ (logand init-val #xfff) (logand other-val #xfff)) #xfff) 1 0)))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (> (+ init-val other-val) #xffff) 1 0)))
    (is (= (get-reg gb :hl) res)
        :ctx ("During opcode ~X the :HL register should hold the result of ~A" op res))))

(deftest test-16bit-add-ops (init-val other-val)
  (loop for op in '((#x09 :bc) (#x19 :de) (#x29 :hl) (#x39 :sp)) do
    (if (eq (cadr op) :hl)
      (test-16bit-add-op (car op) (cadr op) init-val init-val (logand (+ init-val init-val) #xffff) (flags-into-byte (calc-16bit-add-flags init-val init-val)))
      (test-16bit-add-op (car op) (cadr op) init-val other-val (logand (+ init-val other-val) #xffff) (flags-into-byte (calc-16bit-add-flags init-val other-val))))))

(deftest test-pop-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-sp #xd000)
         (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (setf (gbcpu-sp cpu) init-sp)
    (push-addr-on-stack cpu gb init-val)
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-sp cpu) init-sp))
    (if (eq reg :af)
    (is (= (flags-into-byte (gbcpu-flags cpu)) (logand init-val #xf0)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags)))
    (is (= (get-reg gb reg) init-val)
        :ctx ("During opcode ~X the ~A register should equal ~A" op reg init-val))))

(deftest test-pop-ops (init-val)
  (loop for op in '((#xc1 :bc) (#xd1 :de) (#xe1 :hl) (#xf1 :af)) do
    (if (= (car op) #xf1)
      (test-pop-op (car op) (cadr op) (logand init-val #xfff0))
      (test-pop-op (car op) (cadr op) init-val))))

(deftest test-push-op (op reg init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-sp #xd000))
    (set-reg gb reg init-val)
    (let ((init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (setf (gbcpu-sp cpu) init-sp)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 1)))
    (is (= (gbcpu-sp cpu) (- init-sp 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (peek-addr-from-stack cpu gb) init-val)
        :ctx ("During opcode ~X the top of stack should equal ~A" op init-val)))))

(deftest test-push-ops (init-val)
  (loop for op in '((#xc5 :bc) (#xd5 :de) (#xe5 :hl) (#xf5 :af)) do
    (if (= (car op) #xf5)
      (test-push-op (car op) (cadr op) (logand init-val #xfff0))
      (test-push-op (car op) (cadr op) init-val))))

(deftest test-adc-ops (init-val other-val)
  (loop for op in '((#x88 :b) (#x89 :c) (#x8a :d) (#x8b :e)
                    (#x8c :h) (#x8d :l) (#x8e :<hl) (#x8f :a)
                    (#xce :imm)) do
    (if (= (car op) #x8f)
      (test-acc-op (car op) (cadr op) init-val init-val (logand (+ init-val init-val) #xff) (flags-into-byte (calc-8bit-add-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logand (+ init-val other-val) #xff) (flags-into-byte (calc-8bit-add-flags init-val other-val))))))

(defun calc-sub-flags (init-val other-val &optional (carry 0))
  (make-gbflags
    :z (if (= (logand (- init-val other-val carry) #xff) #x0) 1 0)
    :n 1
    :h (if (< (logand init-val #xf) (logand (+ other-val carry) #xf)) 1 0)
    :c (if (< init-val (+ other-val carry)) 1 0)))

(deftest test-sub-ops (init-val other-val)
  (loop for op in '((#x90 :b) (#x91 :c) (#x92 :d) (#x93 :e)
                    (#x94 :h) (#x95 :l) (#x96 :<hl) (#x97 :a)
                    (#xd6 :imm)) do
    (if (= (car op) #x97)
      (test-acc-op (car op) (cadr op) init-val init-val (logand (- init-val init-val) #xff) (flags-into-byte (calc-sub-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logand (- init-val other-val) #xff) (flags-into-byte (calc-sub-flags init-val other-val))))))

(deftest test-sbc-ops (init-val other-val)
  (loop for op in '((#x98 :b) (#x99 :c) (#x9a :d) (#x9b :e)
                    (#x9c :h) (#x9d :l) (#x9e :<hl) (#x9f :a)
                    (#xde :imm)) do
    (if (= (car op) #x9f)
      (test-acc-op (car op) (cadr op) init-val init-val (logand (- init-val init-val) #xff) (flags-into-byte (calc-sub-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logand (- init-val other-val) #xff) (flags-into-byte (calc-sub-flags init-val other-val))))))

(defun calc-and-flags (init-val other-val)
  (make-gbflags
    :z (if (= (logand init-val other-val) #x0) 1 0)
    :n  0
    :h  1
    :c  0))

(deftest test-and-ops (init-val other-val)
  (loop for op in '((#xa0 :b) (#xa1 :c) (#xa2 :d) (#xa3 :e)
                    (#xa4 :h) (#xa5 :l) (#xa6 :<hl) (#xa7 :a)
                    (#xe6 :imm)) do
    (if (= (car op) #xa7)
      (test-acc-op (car op) (cadr op) init-val init-val (logand init-val init-val) (flags-into-byte (calc-and-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logand init-val other-val) (flags-into-byte (calc-and-flags init-val other-val))))))

(defun calc-xor-flags (init-val other-val)
  (make-gbflags
    :z (if (= (logxor init-val other-val) #x0) 1 0)
    :n  0
    :h  0
    :c  0))

(deftest test-xor-ops (init-val other-val)
  (loop for op in '((#xa8 :b) (#xa9 :c) (#xaa :d) (#xab :e)
                    (#xac :h) (#xad :l) (#xae :<hl) (#xaf :a)
                    (#xee :imm)) do
    (if (= (car op) #xaf)
      (test-acc-op (car op) (cadr op) init-val init-val (logxor init-val init-val) (flags-into-byte (calc-xor-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logxor init-val other-val) (flags-into-byte (calc-xor-flags init-val other-val))))))

(defun calc-or-flags (init-val other-val)
  (make-gbflags
    :z (if (= (logior init-val other-val) #x0) 1 0)
    :n  0
    :h  0
    :c  0))

(deftest test-or-ops (init-val other-val)
  (loop for op in '((#xb0 :b) (#xb1 :c) (#xb2 :d) (#xb3 :e)
                    (#xb4 :h) (#xb5 :l) (#xb6 :<hl) (#xb7 :a)
                    (#xf6 :imm)) do
    (if (= (car op) #xb7)
      (test-acc-op (car op) (cadr op) init-val init-val (logior init-val init-val) (flags-into-byte (calc-or-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val (logior init-val other-val) (flags-into-byte (calc-or-flags init-val other-val))))))

(deftest test-cp-ops (init-val other-val)
  (loop for op in '((#xb8 :b) (#xb9 :c) (#xba :d) (#xbb :e)
                    (#xbc :h) (#xbd :l) (#xbe :<hl) (#xbf :a)
                    (#xfe :imm)) do
    (if (= (car op) #xbf)
      (test-acc-op (car op) (cadr op) init-val init-val init-val (flags-into-byte (calc-sub-flags init-val init-val)))
      (test-acc-op (car op) (cadr op) init-val other-val init-val (flags-into-byte (calc-sub-flags init-val other-val))))))

(deftest test-himem-load-op (op dest src fin-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (when (or (eq src :imm) (eq dest :imm))
      (set-reg gb :imm #x00))
    (if (eq src :a)
      (set-reg gb src fin-val)
      (write-memory-at-addr gb (+ #xff00 (get-reg gb src)) fin-val))
    (step-cpu cpu gb)
    (if (or (eq src :imm) (eq dest :imm))
      (is (= (gbcpu-pc cpu) (+ init-pc 2)))
      (is (= (gbcpu-pc cpu) (+ init-pc 1))))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (if (eq dest :a)
      (is (= (get-reg gb dest) fin-val))
      (is (= (read-memory-at-addr gb (+ #xff00 (get-reg gb dest))) fin-val)))))

(deftest test-himem-load-ops (fin-val)
  (loop for op in '((#xe0 :imm :a) (#xe2 :c :a) (#xf0 :a :imm) (#xf2 :a :c)) do
        (test-himem-load-op (car op) (cadr op) (caddr op) fin-val)))

(deftest test-jr-op (op src rel-addr init-flags flag-cond?)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000))
    (setf (gbcpu-flags cpu) init-flags)
    (let ((init-flags-byte (flags-into-byte (gbcpu-flags cpu))))
      (write-memory-at-addr gb init-pc op)
      (setf (gbcpu-pc cpu) init-pc)
      (set-reg gb src rel-addr)
      (step-cpu cpu gb)
      (if flag-cond?
        (is (= (gbcpu-pc cpu) (+ init-pc 2 rel-addr)))
        (is (= (gbcpu-pc cpu) (+ init-pc 2))))
      (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags-byte)))))

(deftest test-jp-op (op src addr init-flags flag-cond?)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000))
    (setf (gbcpu-flags cpu) init-flags)
    (let ((init-flags-byte (flags-into-byte (gbcpu-flags cpu))))
      (write-memory-at-addr gb init-pc op)
      (setf (gbcpu-pc cpu) init-pc)
      (set-reg gb src addr)
      (step-cpu cpu gb)
      (if flag-cond?
        (is (= (gbcpu-pc cpu) addr))
        (is (= (gbcpu-pc cpu) (+ init-pc 3))))
      (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags-byte)))))

(deftest test-jp-ops ()
  (let ((flags (make-gbflags)))
    (test-jr-op #x18 :imm #x7f flags t)
    (test-jr-op #x20 :imm #x7f flags (= (gbflags-z flags) 0))
    (test-jr-op #x28 :imm #x7f flags (= (gbflags-z flags) 1))
    (test-jr-op #x30 :imm #x7f flags (= (gbflags-c flags) 0))
    (test-jr-op #x38 :imm #x7f flags (= (gbflags-c flags) 1))
    (test-jp-op #xc2 :imm16 #xc500 flags (= (gbflags-z flags) 0))
    (test-jp-op #xc3 :imm16 #xc500 flags t)
    (test-jp-op #xca :imm16 #xc500 flags (= (gbflags-z flags) 1))
    (test-jp-op #xd2 :imm16 #xc500 flags (= (gbflags-c flags) 0))
    (test-jp-op #xda :imm16 #xc500 flags (= (gbflags-c flags) 1))))

(deftest test-call-op (op src addr init-flags flag-cond?)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-sp #xd000))
    (setf (gbcpu-flags cpu) init-flags)
    (let ((init-flags-byte (flags-into-byte (gbcpu-flags cpu))))
      (write-memory-at-addr gb init-pc op)
      (setf (gbcpu-pc cpu) init-pc)
      (setf (gbcpu-sp cpu) init-sp)
      (set-reg gb src addr)
      (step-cpu cpu gb)
      (if flag-cond?
        (progn (is (= (gbcpu-pc cpu) addr))
               (is (= (gbcpu-sp cpu) (- init-sp 2)))
               (is (= (peek-addr-from-stack cpu gb) (+ init-pc 3))))
        (progn (is (= (gbcpu-pc cpu) (+ init-pc 3)))
               (is (= (gbcpu-sp cpu) init-sp))))
      (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags-byte)))))

(deftest test-call-ops ()
  (let ((flags (make-gbflags)))
    (test-call-op #xc4 :imm16 #xc500 flags (= (gbflags-z flags) 0))
    (test-call-op #xcc :imm16 #xc500 flags (= (gbflags-z flags) 1))
    (test-call-op #xcd :imm16 #xc500 flags t)
    (test-call-op #xd4 :imm16 #xc500 flags (= (gbflags-c flags) 0))
    (test-call-op #xdc :imm16 #xc500 flags (= (gbflags-c flags) 1))))

(deftest test-ret-op (op addr init-flags flag-cond?)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-sp #xd000))
    (setf (gbcpu-flags cpu) init-flags)
    (let ((init-flags-byte (flags-into-byte (gbcpu-flags cpu))))
      (write-memory-at-addr gb init-pc op)
      (setf (gbcpu-pc cpu) init-pc)
      (setf (gbcpu-sp cpu) init-sp)
      (push-addr-on-stack cpu gb addr)
      (step-cpu cpu gb)
      (if flag-cond?
        (progn (is (= (gbcpu-pc cpu) addr))
               (is (= (gbcpu-sp cpu) init-sp)))
        (progn (is (= (gbcpu-pc cpu) (+ init-pc 1)))
               (is (= (gbcpu-sp cpu) (- init-sp 2)))))
      (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags-byte)))))

(deftest test-ret-ops ()
  (let ((flags (make-gbflags)))
    (test-ret-op #xc0 #xc500 flags (= (gbflags-z flags) 0))
    (test-ret-op #xc8 #xc500 flags (= (gbflags-z flags) 1))
    (test-ret-op #xc9 #xc500 flags t)
    (test-ret-op #xd0 #xc500 flags (= (gbflags-c flags) 0))
    (test-ret-op #xd8 #xc500 flags (= (gbflags-c flags) 1))
    (test-ret-op #xd9 #xc500 flags t)))

(deftest test-rst-op (op addr)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-sp #xd000))
    (let ((init-flags (flags-into-byte (gbcpu-flags cpu))))
    (write-memory-at-addr gb init-pc op)
    (setf (gbcpu-pc cpu) init-pc)
    (setf (gbcpu-sp cpu) init-sp)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) addr))
    (is (= (gbcpu-sp cpu) (- init-sp 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (peek-addr-from-stack cpu gb) (+ init-pc 1))))))

(deftest test-rst-ops ()
  (loop for op in '((#xc7 #x00) (#xcf #x08) (#xd7 #x10) (#xdf #x18)
                    (#xe7 #x20) (#xef #x28) (#xf7 #x30) (#xff #x38)) do
        (test-rst-op (car op) (cadr op))))

;; CB Prefixed Ops
(deftest test-rlc-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val 1) #xff) (ash init-val -7))))
    (write-memory-at-addr gb init-pc (car op))
    (write-memory-at-addr gb (+ init-pc 1) (cadr op))
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op (cadr op)) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op (cadr op))) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x80) #x80) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-rlc-ops (init-val)
  (loop for op from #x00 to #x07 do
        (test-rlc-op (list #xcb op) init-val)))

(deftest test-rrc-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val -1) #xff) (ash (logand init-val #x1) 7))))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-rrc-ops (init-val)
  (loop for op from #x08 to #x0f do
        (test-rrc-op op init-val)))

(deftest test-rl-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (carry (gbflags-c (gbcpu-flags cpu)))
         (res (logior (logand (ash init-val 1) #xff) carry)))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x80) #x80) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-rl-ops (init-val)
  (loop for op from #x10 to #x17 do
        (test-rl-op op init-val)))

(deftest test-rr-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (carry (gbflags-c (gbcpu-flags cpu)))
         (res (logior (logand (ash init-val -1) #xff) (ash carry 7))))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-rr-ops (init-val)
  (loop for op from #x18 to #x1f do
        (test-rr-op op init-val)))

(deftest test-sla-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logand (ash init-val 1) #xff)))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x80) #x80) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-sla-ops (init-val)
  (loop for op from #x20 to #x27 do
        (test-sla-op op init-val)))

(deftest test-sra-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val -1) #xff) (logand init-val #x80))))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-sra-ops (init-val)
  (loop for op from #x28 to #x2f do
        (test-sra-op op init-val)))

(deftest test-swap-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logior (logand (ash init-val -4) #xf) (ash (logand init-val #xf) 4))))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) 0))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= init-val #x0) 1 0)))))

(deftest test-swap-ops (init-val)
  (loop for op from #x30 to #x37 do
        (test-swap-op op init-val)))

(deftest test-srl-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (res (logand (ash init-val -1) #xff)))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (get-reg gb (get-src-reg-from-op op)) res))
    (is (= (gbflags-n (gbcpu-flags cpu)) 0))
    (is (= (gbflags-h (gbcpu-flags cpu)) 0))
    (is (= (gbflags-c (gbcpu-flags cpu)) (if (= (logand init-val #x01) #x01) 1 0)))
    (is (= (gbflags-z (gbcpu-flags cpu))
           (if (= res #x0) 1 0)))))

(deftest test-srl-ops (init-val)
  (loop for op from #x38 to #x3f do
        (test-srl-op op init-val)))

(deftest test-bit-op (op init-val)
  (let* ((gb (make-gb))
         (cpu (gb-cpu gb))
         (init-pc #xc000)
         (init-flags (copy-gbflags (gbcpu-flags cpu)))
         (bit-pos (logand (ash op -3) #x7)))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
      (set-reg gb (get-src-reg-from-op op) init-val)
      (step-cpu cpu gb)
      (is (= (gbcpu-pc cpu) (+ init-pc 2)))
      (is (= (gbflags-n (gbcpu-flags cpu)) 0))
      (is (= (gbflags-h (gbcpu-flags cpu)) 1))
      (is (= (gbflags-c (gbcpu-flags cpu)) (gbflags-c init-flags)))
      (is (= (gbflags-z (gbcpu-flags cpu))
             (if (= (logand (get-reg gb (get-src-reg-from-op op)) (ash 1 bit-pos)) #x0) 1 0)))))

(deftest test-bit-ops (init-val)
  (loop for op from #x40 to #x7f do
        (test-bit-op op init-val)))

(deftest test-reset-bit-op (op init-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu)))
        (bit-pos (logand (ash op -3) #x7)))
  (write-memory-at-addr gb init-pc #xcb)
  (write-memory-at-addr gb (+ init-pc 1) op)
  (set-reg-pair-hl-to-val cpu #xc100)
  (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (= (logand (get-reg gb (get-src-reg-from-op op)) (ash 1 bit-pos)) #x0)
        :ctx ("During opcode ~X the ~A register should have bit ~A reset" op (get-src-reg-from-op op) bit-pos))))

(deftest test-reset-bit-ops (init-val)
  (loop for op from #x80 to #xbf do
        (test-reset-bit-op op init-val)))

(deftest test-set-bit-op (op init-val)
  (let* ((gb (make-gb))
        (cpu (gb-cpu gb))
        (init-pc #xc000)
        (init-flags (flags-into-byte (gbcpu-flags cpu)))
          (bit-pos (logand (ash op -3) #x7)))
    (write-memory-at-addr gb init-pc #xcb)
    (write-memory-at-addr gb (+ init-pc 1) op)
    (set-reg-pair-hl-to-val cpu #xc100)
    (setf (gbcpu-pc cpu) init-pc)
    (set-reg gb (get-src-reg-from-op op) init-val)
    (step-cpu cpu gb)
    (is (= (gbcpu-pc cpu) (+ init-pc 2)))
    (is (= (flags-into-byte (gbcpu-flags cpu)) init-flags))
    (is (> (logand (get-reg gb (get-src-reg-from-op op)) (ash 1 bit-pos)) #x00)
        :ctx ("During opcode ~X the ~A register should have bit ~A set" op (get-src-reg-from-op op) bit-pos))))

(deftest test-set-bit-ops (init-val)
  (loop for op from #xc0 to #xff do
        (test-set-bit-op op init-val)))

(defun get-reg (gb reg)
  (let ((cpu (gb-cpu gb)))
    (case reg
      (:b (gbcpu-b cpu))
      (:c (gbcpu-c cpu))
      (:bc (logior (ash (gbcpu-b cpu) 8) (gbcpu-c cpu)))
      (:<bc (get-byte-at-bc cpu gb))
      (:d (gbcpu-d cpu))
      (:e (gbcpu-e cpu))
      (:de (logior (ash (gbcpu-d cpu) 8) (gbcpu-e cpu)))
      (:<de (get-byte-at-de cpu gb))
      (:h (gbcpu-h cpu))
      (:l (gbcpu-l cpu))
      (:hl (logior (ash (gbcpu-h cpu) 8) (gbcpu-l cpu)))
      (:<hl (get-byte-at-hl cpu gb))
      (:a (gbcpu-a cpu))
      (:af (logior (ash (gbcpu-a cpu) 8) (flags-into-byte (gbcpu-flags cpu))))
      (:sp (gbcpu-sp cpu))
      (:imm (read-memory-at-addr gb (+ (gbcpu-pc cpu) 1)))
      (:imm16 (logior (read-memory-at-addr gb (+ (gbcpu-pc cpu) 1))
                      (ash (read-memory-at-addr gb (+ (gbcpu-pc cpu) 2)) 8))))))

(defun set-reg (gb reg val)
  (let ((cpu (gb-cpu gb)))
    (case reg
      (:b (setf (gbcpu-b cpu) val))
      (:c (setf (gbcpu-c cpu) val))
      (:bc (setf (gbcpu-b cpu) (logand (ash val -8) #xff)
                 (gbcpu-c cpu) (logand val #xff)))
      (:<bc (set-byte-at-bc cpu gb val))
      (:d (setf (gbcpu-d cpu) val))
      (:e (setf (gbcpu-e cpu) val))
      (:de (setf (gbcpu-d cpu) (logand (ash val -8) #xff)
                 (gbcpu-e cpu) (logand val #xff)))
      (:<de (set-byte-at-de cpu gb val))
      (:h (setf (gbcpu-h cpu) val))
      (:l (setf (gbcpu-l cpu) val))
      (:hl (setf (gbcpu-h cpu) (logand (ash val -8) #xff)
                 (gbcpu-l cpu) (logand val #xff)))
      (:<hl (set-byte-at-hl cpu gb val))
      (:a (setf (gbcpu-a cpu) val))
      (:af (setf (gbcpu-a cpu) (logand (ash val -8) #xff)
                 (gbcpu-flags cpu) (flags-from-byte (logand val #xf0))))
      (:sp (setf (gbcpu-sp cpu) val))
      (:imm (write-memory-at-addr gb (+ (gbcpu-pc cpu) 1) val))
      (:imm16 (write-memory-at-addr gb (+ (gbcpu-pc cpu) 1) (logand val #xff))
              (write-memory-at-addr gb (+ (gbcpu-pc cpu) 2) (ash val -8))))))

(defun get-dest-reg-from-op (op)
  (case (logand op #xf8)
    (#x40 :b)
    (#x48 :c)
    (#x50 :d)
    (#x58 :e)
    (#x60 :h)
    (#x68 :l)
    (#x70 :<hl)
    (#x78 :a)))

(defun get-src-reg-from-op (op)
  (case (logand op #x7)
    (#x0 :b)
    (#x1 :c)
    (#x2 :d)
    (#x3 :e)
    (#x4 :h)
    (#x5 :l)
    (#x6 :<hl)
    (#x7 :a)))
