

(in-package :clboy)

(defstruct gbcart
  (rom (make-array #x8000 :element-type '(unsigned-byte 8)))
  (ram (make-array #x2000 :initial-element 0 :element-type '(unsigned-byte 8)))
  (carttype 0)
  (ramon nil :type boolean)
  (rombank 1)
  (rommask 1)
  (rammask 1)
  (rambank 0)
  (mode 0))

(defun replace-memory-with-rom (cart file)
  (let ((rom (read-rom-data-from-file file)))
    (setf (gbcart-rom cart) (make-array (length rom) :element-type '(unsigned-byte 8)))
    (replace (gbcart-rom cart) rom)))

(defun get-carttype-from-rom (cart) (setf (gbcart-carttype cart) (cart-read-memory-at-addr cart #x147)))
(defun get-rommask-from-rom (cart) (setf (gbcart-rommask cart) (- (ash #x02 (cart-read-memory-at-addr cart #x148)) 1)))
(defun get-ramsize-from-rom (cart)
  (let ((rambanks (case (aref (gbcart-rom cart) #x0149)
                   (#x00 0)
                   (#x02 1)
                   (#x03 4)
                   (#x04 16)
                   (#x05 8))))
    (if (> rambanks 0) (setf (gbcart-ram cart) (make-array (* rambanks #x2000) :element-type '(unsigned-byte 8))))
    (setf (gbcart-rammask cart) (- rambanks 1))))

(defun cart-write-memory-at-addr (cart addr val)
  (case (logand addr #xf000)
    ((#x0000 #x1000 #x2000 #x3000 #x4000 #x5000 #x6000 #x7000)
     (case (gbcart-carttype cart)
       ((1 2 3) (cart-mbc1-write cart addr val))
       ))
    ((#xa000 #xb000)
     (if (gbcart-ramon cart) (setf (aref (gbcart-ram cart) (+ (gbcart-ram-offset cart) (logand addr #x1fff))) val)))))

(defun cart-read-memory-at-addr (cart addr)
  (case (logand addr #xf000)
    ((#x0000 #x1000 #x2000 #x3000)
      (aref (gbcart-rom cart) (+ (* (logand (gbcart-rombank cart) #x60) #x4000) (logand addr #x3fff))))
    ((#x4000 #x5000 #x6000 #x7000)
      (aref (gbcart-rom cart) (+ (* (gbcart-rombank cart) #x4000) (logand addr #x3fff))))
    ((#xa000 #xb000)
      (if (gbcart-ramon cart) (aref (gbcart-ram cart) (+ (* (gbcart-rambank cart) #x2000) (logand addr #x1fff))) #xff))))

(defun cart-mbc1-write (cart addr val)
  (case (logand addr #xf000)
    ((#x0000 #x1000)
     (case (gbcart-carttype cart)
       ((2 3) (setf (gbcart-ramon cart) (= (logand val #xf) #x0a)))))
    ((#x2000 #x3000)
     (case (gbcart-carttype cart)
       ((1 2 3)
         (let* ((lower5bits (logand val #x1f))
               (rombank (logand (+ (logand (gbcart-rombank cart) #x60) (if (> lower5bits 1) lower5bits 1)) (gbcart-rommask cart))))
           (setf (gbcart-rombank cart) rombank)))))
    ((#x4000 #x5000)
     (case (gbcart-carttype cart)
       ((1 2 3)
         (let ((rombank (logand (+ (logand (gbcart-rombank cart) #x1f) (ash (logand val #x03) 5)) (gbcart-rommask cart))))
         (setf (gbcart-rombank cart) rombank))
         (when (= (gbcart-mode cart) #x01)
           (let ((rambank (logand (logand (ash val -5) #x03) (gbcart-rammask cart))))
             (setf (gbcart-rambank cart) rambank))))))
    ((#x6000 #x7000)
     (case (gbcart-carttype cart)
       ((2 3) (setf (gbcart-mode cart) (logand val #x01)))))))


