

(in-package :clboy)

(defconstant +sample-rate+ 44100)
(defconstant +audio-buffer-size+ 256)
(defconstant +cycles-per-sample+ (floor +cpu-speed+ +sample-rate+))
(defconstant +cycles-frame-seq-step+ (floor +cpu-speed+ 512))

(defstruct gbspu
  (ch1 (make-channel))
  (ch2 (make-channel))
  (ch3 (make-channel))
  (ch4 (make-channel))
  (wave-ram (make-array 16 :initial-element 0 :element-type '(unsigned-byte 8)))
  (ena? nil :type boolean)
  (prev-angle 0)
  (buffer (static-vectors:make-static-vector +audio-buffer-size+ :element-type 'single-float :initial-element 0.0))
  (buffer-index 0)
  (frame-sequencer-delay 0)
  (frame-sequencer 0)
  (delay 0)
  (cycles 0)
  )

(defstruct channel
  (r0 0 :type (unsigned-byte 8))
  (r1 0 :type (unsigned-byte 8))
  (r2 0 :type (unsigned-byte 8))
  (r3 0 :type (unsigned-byte 8))
  (r4 0 :type (unsigned-byte 8))
  (seq #x0f)
  (timer 0)
  (len 0)
  (vol 0)
  (env-tick 0)
  (sweep-period 0)
  (cur-bit 0)
  (cur-addr 0)
  (lfsr 0 :type (unsigned-byte 15))
  (ena? nil :type boolean)
  (dac-ena? t :type boolean)
  )

(defun spu-read-memory-at-addr (spu addr)
  (case (logand addr #xff)
    ((#x10 #x11 #x12 #x13 #x14      #x16 #x17
      #x18 #x19 #x1a #x1b #x1c #x1d #x1e #x1f
      #x20 #x21 #x22 #x23)
     (spu-read-sound-channel spu addr))
    (#x24 #xff)
    (#x25 #xff)
    (#x26 (read-sound-ena spu))
    ((#x30 #x31 #x32 #x33 #x34 #x35 #x36 #x37
      #x38 #x39 #x3a #x3b #x3c #x3d #x3e #x3f)
     (aref (gbspu-wave-ram spu) (logand addr #xf)))
    (otherwise #xff)))

(defun spu-write-memory-at-addr (spu addr val)
  (case (logand addr #xff)
    ((#x10 #x11 #x12 #x13 #x14      #x16 #x17
      #x18 #x19 #x1a #x1b #x1c #x1d #x1e #x1f
      #x20 #x21 #x22 #x23)
      (spu-write-sound-channel spu addr val))
    (#x24 ())
    (#x25 ())
    (#x26 (setf (gbspu-ena? spu) (= (logand val #x80) #x80)))
    ((#x30 #x31 #x32 #x33 #x34 #x35 #x36 #x37
      #x38 #x39 #x3a #x3b #x3c #x3d #x3e #x3f)
     (setf (aref (gbspu-wave-ram spu) (logand addr #xf)) val))
    (otherwise ())))

(defun spu-read-sound-channel (spu addr)
  (case addr
    (#xff10 (channel-r0 (gbspu-ch1 spu)))
    (#xff11 (channel-r1 (gbspu-ch1 spu)))
    (#xff12 (channel-r2 (gbspu-ch1 spu)))
    (#xff13 (channel-r3 (gbspu-ch1 spu)))
    (#xff14 (channel-r4 (gbspu-ch1 spu)))
    (#xff16 (channel-r1 (gbspu-ch2 spu)))
    (#xff17 (channel-r2 (gbspu-ch2 spu)))
    (#xff18 (channel-r3 (gbspu-ch2 spu)))
    (#xff19 (channel-r4 (gbspu-ch2 spu)))
    (#xff1a (channel-r0 (gbspu-ch3 spu)))
    (#xff1b (channel-r1 (gbspu-ch3 spu)))
    (#xff1c (channel-r2 (gbspu-ch3 spu)))
    (#xff1d (channel-r3 (gbspu-ch3 spu)))
    (#xff1e (channel-r4 (gbspu-ch3 spu)))
    (#xff20 (channel-r1 (gbspu-ch4 spu)))
    (#xff21 (channel-r2 (gbspu-ch4 spu)))
    (#xff22 (channel-r3 (gbspu-ch4 spu)))
    (#xff23 (channel-r4 (gbspu-ch4 spu)))
    (otherwise #xff)))

(defun spu-write-sound-channel (spu addr val)
  (case addr
    (#xff10 (setf (channel-r0 (gbspu-ch1 spu)) val))
    (#xff11 (set-channel-r1 (gbspu-ch1 spu) val))
    (#xff12 (set-channel-r2 (gbspu-ch1 spu) val))
    (#xff13 (set-channel-r3 (gbspu-ch1 spu) val))
    (#xff14 (set-channel-r4 (gbspu-ch1 spu) val))
    (#xff16 (set-channel-r1 (gbspu-ch2 spu) val))
    (#xff17 (set-channel-r2 (gbspu-ch2 spu) val))
    (#xff18 (set-channel-r3 (gbspu-ch2 spu) val))
    (#xff19 (set-channel-r4 (gbspu-ch2 spu) val))
    (#xff1a (set-wave-channel-r0 (gbspu-ch3 spu) val))
    (#xff1b (set-wave-channel-r1 (gbspu-ch3 spu) val))
    (#xff1c (set-wave-channel-r2 (gbspu-ch3 spu) val))
    (#xff1d (set-channel-r3 (gbspu-ch3 spu) val))
    (#xff1e (set-wave-channel-r4 (gbspu-ch3 spu) val))
    (#xff20 (set-channel-r1 (gbspu-ch4 spu) val))
    (#xff21 (set-channel-r2 (gbspu-ch4 spu) val))
    (#xff22 (set-channel-r3 (gbspu-ch4 spu) val))
    (#xff23 (set-channel-r4 (gbspu-ch4 spu) val))
    (otherwise ())))

(defun set-wave-channel-r0 (channel val)
  (setf (channel-r0 channel) val
        (channel-dac-ena? channel) (= (logand val #x80) #x80)))
(defun set-wave-channel-r1 (channel val)
  (setf (channel-r1 channel) val
        (channel-len channel) (- 256 val)))
(defun set-wave-channel-r2 (channel val)
  (setf (channel-r2 channel) val
        (channel-vol channel)
        (case (logand (ash val -5) #x3)
          (#x0 4)
          (#x1 0)
          (#x2 1)
          (#x3 2))))

(defun set-wave-channel-r4 (channel val)
    (setf (channel-r4 channel) val)
    (if (> val #x7f) (setf (channel-ena? channel) t))
    (when (= (logand val #x40) #x40)
      (setf (channel-len channel) (channel-r1 channel))))

(defun set-channel-r1 (channel val)
  (setf (channel-r1 channel) val
        (channel-len channel) (logand val #x1f)
        (channel-seq channel) (get-channel-seq-from-byte val)))

(defun get-channel-seq-from-byte (val)
  (let ((seq-index (ash val -6)))
    (case seq-index
      (#x0 #x7f)
      (#x1 #x3f)
      (#x2 #x0f)
      (#x3 #x03))))

(defun set-channel-r2 (channel val)
  (setf (channel-r2 channel) val
        (channel-vol channel) (logand (ash val -4) #xf)
        (channel-env-tick channel) (logand val #x7)))

(defun set-channel-r3 (channel val)
  (setf (channel-r3 channel) val))

(defun set-channel-r4 (channel val)
    (setf (channel-r4 channel) val)
    (when (> val #x7f)
      (setf (channel-ena? channel) t
            (channel-timer channel) (* (channel-freq channel) 4)
            (channel-vol channel) (logand (ash (channel-r2 channel) -4) #xf)
            (channel-env-tick channel) (logand (channel-r2 channel) #x7)
            (channel-sweep-period channel) (logand (channel-r0 channel) #x7)
            (channel-lfsr channel) #xff)
      (if (= (channel-len channel) 0)
        (setf (channel-len channel) (logand (channel-r1 channel) #x1f)))))

(defun read-sound-ena (spu)
  (+ (ash (bool-as-bit (gbspu-ena? spu)) 7)
     (ash (bool-as-bit (channel-ena? (gbspu-ch4 spu))) 3)
     (ash (bool-as-bit (channel-ena? (gbspu-ch3 spu))) 2)
     (ash (bool-as-bit (channel-ena? (gbspu-ch2 spu))) 1)
     (bool-as-bit (channel-ena? (gbspu-ch1 spu)))))

(defun channel-freq (channel)
  (let ((freq-msb (ash (logand (channel-r4 channel) #x7) 8))
        (freq-lsb (channel-r3 channel)))
    (- 2048 (logior freq-msb freq-lsb))))

(defun set-channel-freq (channel freq)
  (let ((freq-msb (logand (ash freq -8) #x7))
        (freq-lsb (logand freq #xff)))
    (setf (channel-r4 channel) (logior (channel-r4 channel) freq-msb)
          (channel-r3 channel) freq-lsb)))

(defun channel-noise-freq (channel)
  (let ((r3-shift (ash (channel-r3 channel) -4))
        (r3-ratio (logand (channel-r3 channel) #x07)))
    (ash (noise-divisor r3-ratio) r3-shift)))

(defun noise-divisor (div-ratio)
  (case div-ratio
    (0 8)
    (1 16)
    (2 32)
    (3 48)
    (4 64)
    (5 80)
    (6 96)
    (7 112)))

(defun gen-lfsr (channel)
	(let* ((lfsr (channel-lfsr channel))
         (xor-res (logxor (ldb (byte 1 0) (logand lfsr #x01)) (ldb (byte 1 0) (logand (ash lfsr -1) #x01))))
         (new-lfsr (logior (logior (ash lfsr -1) (ash xor-res 14)))))
    (if (= (logand (channel-r3 channel) #x8) #x8)
      (logand (logior new-lfsr (ash xor-res 6)) #x7f)
      new-lfsr)))

(defun step-sqare-channel (channel spu)
      (when (and (= (logand (gbspu-frame-sequencer spu) #x3) #x2)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (or (> (logand (channel-r0 channel) #x7) 0)
                     (> (logand (ash (channel-r0 channel) -4) #x7) 0)))
        (step-channel-sweep channel))

      (step-channel-seq channel)

      (when (and (= (mod (gbspu-frame-sequencer spu) 2) 0)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (= (logand (channel-r4 channel) #x40) #x40))
        (step-channel-len channel)
        )

      (when (and (= (gbspu-frame-sequencer spu) 7)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (> (logand (channel-r2 channel) 7) 0))
        (step-channel-env channel)
        ))

(defun step-wave-channel (channel spu)
      (step-wave-channel-seq channel)

      (when (= (channel-cur-bit channel) 0)
        (incf (channel-cur-addr channel))
        (if (> (channel-cur-addr channel) #xf) (setf (channel-cur-addr channel) 0))
        (setf (channel-seq channel) (spu-read-memory-at-addr spu (+ #xff30 (channel-cur-addr channel)))))

      (when (and (= (mod (gbspu-frame-sequencer spu) 2) 0)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (= (logand (channel-r4 channel) #x40) #x40))
        (step-channel-len channel)))

(defun step-noise-channel (channel spu)
      (step-noise-channel-seq channel)

      (when (and (= (mod (gbspu-frame-sequencer spu) 2) 0)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (= (logand (channel-r4 channel) #x40) #x40))
        (step-channel-len channel)
        )

      (when (and (= (gbspu-frame-sequencer spu) 7)
                 (= (gbspu-frame-sequencer-delay spu) 0)
                 (> (logand (channel-r2 channel) 7) 0))
        (step-channel-env channel)
        ))

(defun step-wave-channel-seq (channel)
  (if (= (channel-timer channel) 0)
    (setf (channel-timer channel) (* (channel-freq channel) 2)
          (channel-cur-bit channel) (mod (+ (channel-cur-bit channel) 1) 2))
    (decf (channel-timer channel))))
(defun get-wave-channel-output (channel)
  (let* ((wave-val
           (logand (ash (channel-seq channel)
                (if (= (channel-cur-bit channel) 0) -4 0)) #xf))
        (wave-val-with-vol (ash wave-val (- 0 (channel-vol channel)))))
    (if (channel-ena? channel)
        (coerce (/ wave-val-with-vol 100) 'single-float)
        0.0)))

(defun step-channel-seq (channel)
  (if (= (channel-timer channel) 0)
    (setf (channel-timer channel) (* (channel-freq channel) 4)
          (channel-cur-bit channel) (mod (+ (channel-cur-bit channel) 1) 8))
    (decf (channel-timer channel))))
(defun get-square-channel-output (channel)
  (if (channel-ena? channel)
      (if (= (logand
              (ash (channel-seq channel) (- 0 (channel-cur-bit channel))) #x1) 0)
        0.0;(coerce (* -1 (/ (channel-vol channel) 100)) 'single-float)
        (coerce (/ (channel-vol channel) 100) 'single-float))
      0.0))

(defun step-noise-channel-seq (channel)
  (if (<= (channel-timer channel) 0)
    (setf (channel-timer channel) (channel-noise-freq channel)
          (channel-lfsr channel) (gen-lfsr channel))
    (decf (channel-timer channel))))
(defun get-noise-channel-output (channel)
  (if (channel-ena? channel)
      (if (= (logand (channel-lfsr channel) #x1) 1)
        0.0
        (coerce (/ (channel-vol channel) 100) 'single-float))
      0.0))

(defun step-channel-len (channel)
    (decf (channel-len channel))
    (if (<= (channel-len channel) 0)
      (setf (channel-ena? channel) nil)))

(defun step-channel-env (channel)
    (decf (channel-env-tick channel))
    (when (<= (channel-env-tick channel) 0)
      (setf (channel-env-tick channel) (logand (channel-r2 channel) #x7))
      (let ((new-vol (+ (channel-vol channel) (if (= (logand (channel-r2 channel) #x8) #x8) 1 -1))))
        (if (and (>= new-vol 0) (<= new-vol 15))
          (setf (channel-vol channel) new-vol)))))

(defun step-channel-sweep (channel)
    (decf (channel-sweep-period channel))
    (when (<= (channel-sweep-period channel) 0)
      (setf (channel-sweep-period channel) (logand (channel-r0 channel) #x7))
      (if (= (channel-sweep-period channel) 0) (setf (channel-sweep-period channel) 8))
      (when (> (logand (channel-r0 channel) #x7) 0)
        (let* ((channel-sweep (logand (channel-r0 channel) #x7))
               (cur-freq (channel-freq channel))
               (new-freq (funcall (if (= (logand (channel-r0 channel) #x8) #x8) #'- #'+) cur-freq (ash cur-freq (- 0 channel-sweep)))))
               (if (< new-freq 2048) (set-channel-freq channel new-freq))))))

(defun run-sound (spu audio-device)
  (loop
    repeat (gbspu-cycles spu) do
    (incf (gbspu-frame-sequencer-delay spu))
    (when (= (gbspu-frame-sequencer-delay spu) +cycles-frame-seq-step+)
      (setf (gbspu-frame-sequencer spu) (mod (+ (gbspu-frame-sequencer spu) 1) 8)
            (gbspu-frame-sequencer-delay spu) 0))
    (incf (gbspu-delay spu))
    (step-sqare-channel (gbspu-ch1 spu) spu)
    (step-sqare-channel (gbspu-ch2 spu) spu)
    (step-wave-channel (gbspu-ch3 spu) spu)
    (step-noise-channel (gbspu-ch4 spu) spu)
    (when (= (gbspu-delay spu) +cycles-per-sample+)
      (setf (gbspu-delay spu) 0)
      (setf (aref (gbspu-buffer spu) (gbspu-buffer-index spu))
              (+(get-square-channel-output (gbspu-ch1 spu))
              (get-square-channel-output (gbspu-ch2 spu))
              (get-wave-channel-output (gbspu-ch3 spu))
              (get-noise-channel-output (gbspu-ch4 spu))))
      (incf (gbspu-buffer-index spu)))
    (when (>= (gbspu-buffer-index spu) +audio-buffer-size+)
      ;(sdl2:queue-audio audio-device (gbspu-buffer spu))
      (sdl2-ffi.functions:sdl-queue-audio
        audio-device
        (static-vectors:static-vector-pointer (gbspu-buffer spu))
        (* +audio-buffer-size+ 4))
      (setf (gbspu-buffer-index spu) 0)
    )))

