
name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin,sbcl,ccl,ccl32,ecl,clisp,allegro,cmucl,abcl]
        os: [ubuntu-latest, arch-linux]

    steps:
      - uses: actions/checkout@v3
  
      - name: install roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

      - name: install quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          ${{ matrix.lisp }} --non-interactive \
               --eval "(load \"~/quicklisp.lisp\")" \
               --eval "(quicklisp-quickstart:install)"
          mkdir -p ~/quicklisp/local-projects/

      - name: checkout cl-sdl2
        run: git clone https://github.com/chrcav/cl-sdl2.git ~/quicklisp/local-projects/

      - name: Run a multi-line script
        run: |
          ln -sf $GITHUB_WORKSPACE ~/quicklisp/local-projects/clboy
          ${{ matrix.lisp }} --non-interactive \
               --eval "(load (merge-pathnames \"quicklisp/setup.lisp\" (user-homedir-pathname)))" \
               --eval "(ql:quickload '(clboy clboy/test))" \
               --eval "(unless (try:passedp (try:try 'clboy-test:test-all)) (uiop:quit 1))"
